"""
Django settings for magicleague project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '956l*8&j&!vjz&x$+ir&l35c+2kt(8xr=hosgxty+wc9tn@ya-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True 

#ALLOWED_HOSTS = ['vsnake', '.mcdillers.com', '127.0.0.1']
ALLOWED_HOSTS = []

#CSRF_COOKIE_SECURE = True
#SESSION_COOKIE_SECURE = True

# Application definition

INSTALLED_APPS = (
    'leaguematches',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'magicleague.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        #TODO: Why absolute path here?
        'DIRS': ['/opt/python/current/app/leaguematches/templates/leaguematches'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'magicleague.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# HACK since Elastic Beanstalk don't use env variables for python?
os.environ['RDS_PORT'] = "5432"
os.environ['RDS_PASSWORD'] = "UBdT!hP5hYJw"
os.environ['RDS_USERNAME'] = "ekajmiller"
os.environ['RDS_DB_NAME'] = "magicleague"
os.environ['RDS_HOSTNAME'] = "magicleague.cjduwx2c3jsg.us-west-2.rds.amazonaws.com"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'HOST': os.environ['RDS_HOSTNAME'],
        'PORT': os.environ['RDS_PORT'],
        'NAME': os.environ['RDS_DB_NAME'],
        'USER': os.environ['RDS_USERNAME'],
        'PASSWORD': os.environ['RDS_PASSWORD'],
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

LOGIN_REDIRECT_URL = "/leaguematches/"
